Repository pacmanproject/pacman, pull requests merged in 2021-02, with the labels that each got.

#46 fixed the scoreboard saving system
  .gitignore
  resources/data/scores/default.json
  src/gui/Gui.java
  src/models/Pacman.java
  src/models/Score.java
  src/models/World.java
  src/util/Scoreboard.java
Labels: bug, enhancement

#47 Scor is now displayed at the bottom
  src/gui/GamePanel.java
  src/gui/Gui.java
Labels: enhancement

#50 major overhaul over map storage, items and other things
  resources/data/maps/Leandro_macht_die_besten_Karten.json
  resources/data/maps/default_map.json
  resources/data/maps/map2.json
  resources/data/maps/map3.json
  src/gui/GamePanel.java
  src/models/Items.java
  src/models/Map.java
  src/models/Pacman.java
  src/models/Score.java
  src/models/World.java
Labels: documentation, enhancement

#51 added items scaling for a better visual experience
  src/gui/GamePanel.java
  src/gui/Gui.java
  src/models/Items.java
  src/models/World.java
Labels: enhancement

#56 moved the hp counter to pacman and improved code readability and perf…
  src/gui/GamePanel.java
  src/gui/Gui.java
  src/models/Pacman.java
Labels: enhancement

#57 New runnable class "Map_Designer"
  src/gui/Map_Designer.java
  src/models/Map.java
Labels: bug, enhancement
