Repository pacmanproject/pacman, pull requests merged in 2021-03, with the labels that each got.

#63 Improved code readability and naming,
  src/gui/Gui.java
  src/gui/Hauptmenue.java
  src/gui/MainMenu.java
  src/util/MapController.java
  src/util/ScoreController.java
Labels: documentation, enhancement

#65 Neue Haupmenue Gui mit editor Start
  Main.java
  src/gui/Gui.java
  src/gui/MainMenu.java
  src/gui/Map_Designer.java
  src/gui/SettingPanel.java
  src/models/Ghost.java
  src/models/Pacman.java
  src/util/GhostController.java
  src/util/KeyController.java
Labels: documentation, enhancement

#66 Slieder to change music volume ind settings panel
  resources/data/maps/Hmm.json
  src/gui/Gui.java
  src/gui/Map_Designer.java
  src/gui/SettingPanel.java
  src/models/Ghost.java
  src/models/Pacman.java
  src/util/GhostController.java
  src/util/KeyController.java
  src/util/MapController.java
  src/util/SoundController.java
Labels: documentation, enhancement

#68 Beta items
  src/gui/GamePanel.java
  src/gui/Gui.java
  src/models/Ghost.java
  src/models/Items.java
  src/models/Pacman.java
Labels: bug, enhancement

#69 Sound effects when events happen
  src/gui/GamePanel.java
  src/gui/Gui.java
  src/gui/SettingPanel.java
  src/models/Pacman.java
  src/util/SoundController.java
Labels: enhancement

#73 Fixed small error and cleaned up imports
  src/gui/Gui.java
  src/gui/MainMenu.java
  src/gui/Map_Designer.java
  src/models/Ghost.java
  src/models/Items.java
  src/models/Pacman.java
  src/models/Score.java
  src/util/GhostController.java
  src/util/MapController.java
  src/util/ScoreController.java
  src/util/SoundController.java
Labels: bug

#74 sounds are no longer earrape
  src/gui/GamePanel.java
  src/gui/SettingPanel.java
  src/util/SoundController.java
Labels: documentation, enhancement

#75 Scoreboard
  src/gui/MainMenu.java
  src/gui/Scoreboard.java
  src/util/ScoreController.java
Labels: enhancement

#76 Added game-sound settings
  resources/data/scores/default.json
  resources/data/settings.json
  src/gui/Gui.java
  src/gui/SettingPanel.java
  src/models/Pacman.java
  src/models/Settings.java
  src/util/SettingsController.java
  src/util/SoundController.java
Labels: documentation, enhancement

#77 Map_designer kommentiert
  src/gui/Map_Designer.java
  src/models/Map.java
Labels: documentation

#78 Gui improvements
  resources/data/maps/Hmm.json
  src/gui/Gui.java
  src/gui/MainMenu.java
  src/gui/SettingPanel.java
Labels: enhancement

#79 code cleanup
  Main.java
  src/gui/GamePanel.java
  src/gui/Gui.java
  src/gui/MainMenu.java
  src/gui/Map_Designer.java
  src/gui/SettingPanel.java
  src/models/Ghost.java
  src/models/Map.java
  src/models/Pacman.java
  src/models/Settings.java
  src/util/GhostController.java
  src/util/KeyController.java
  src/util/MapController.java
  src/util/SettingsController.java
  src/util/SoundController.java
Labels: documentation

#80 music start mit spiel start
  src/util/GhostController.java
  src/util/KeyController.java
  src/util/ScoreController.java
  src/util/SettingsController.java
Labels: documentation

#83 Added new Item and Code cleanup
  resources/data/maps/default_map.json
  src/gui/GamePanel.java
  src/gui/Gui.java
  src/models/Ghost.java
  src/models/Items.java
  src/models/Pacman.java
  src/util/MapController.java
Labels: documentation, enhancement

#84 Deleated todos
  Main.java
  src/gui/GamePanel.java
  src/gui/MainMenu.java
  src/models/Items.java
  src/models/Map.java
  src/models/Pacman.java
Labels: documentation, enhancement

#86 music improvment
  resources/img/General Sprites.png
  src/models/Items.java
Labels: enhancement
